services:
  discord-bot:
    build:
      context: ./discord
      dockerfile: ./Dockerfile
    restart: always
    env_file: .env
  telegram-bot:
    build:
      context: ./telegram
      dockerfile: ./Dockerfile
    restart: always
    env_file: .env
